In [1]:
import numpy as np

# Hobby names
hobby_names = np.array([
    "Reading",
    "Gaming",
    "Music",
    "Sports",
    "Dancing",
    "Cooking",
    "Drawing",
    "Photography"
])

# Dataset: hours spent per week on each hobby
data = np.array([
    [8, 6, 9, 5, 4, 3, 6, 2],
    [7, 9, 6, 8, 3, 4, 2, 5],
    [9, 5, 8, 7, 2, 3, 7, 4],
    [6, 8, 7, 9, 6, 4, 3, 2],
    [5, 7, 9, 6, 4, 8, 5, 3],
    [8, 9, 7, 8, 5, 3, 2, 6],
    [7, 6, 8, 9, 8, 4, 5, 3],
    [9, 8, 6, 7, 3, 2, 8, 6],
    [6, 5, 7, 8, 9, 6, 4, 3],
    [8, 7, 9, 6, 4, 9, 7, 2]
])

# Preferred hobby of each student
preferred_hobby = np.array([
    "Music",
    "Gaming",
    "Reading",
    "Sports",
    "Cooking",
    "Gaming",
    "Dancing",
    "Reading",
    "Dancing",
    "Cooking"
])

# Display dataset
print("Hobby Dataset:")
print(data)

print("\nHobby Names:")
print(hobby_names)

print("\nPreferred Hobby:")
print(preferred_hobby)

# Mean of each hobby
print("\nMean:")
print(np.mean(data, axis=0))

# Median of each hobby
print("\nMedian:")
print(np.median(data, axis=0))

# Standard deviation
print("\nStandard Deviation:")
print(np.std(data, axis=0))

# Maximum
print("\nMaximum:")
print(np.max(data, axis=0))

# Minimum
print("\nMinimum:")
print(np.min(data, axis=0))


Hobby Dataset:
[[8 6 9 5 4 3 6 2]
 [7 9 6 8 3 4 2 5]
 [9 5 8 7 2 3 7 4]
 [6 8 7 9 6 4 3 2]
 [5 7 9 6 4 8 5 3]
 [8 9 7 8 5 3 2 6]
 [7 6 8 9 8 4 5 3]
 [9 8 6 7 3 2 8 6]
 [6 5 7 8 9 6 4 3]
 [8 7 9 6 4 9 7 2]]

Hobby Names:
['Reading' 'Gaming' 'Music' 'Sports' 'Dancing' 'Cooking' 'Drawing'
 'Photography']

Preferred Hobby:
['Music' 'Gaming' 'Reading' 'Sports' 'Cooking' 'Gaming' 'Dancing'
 'Reading' 'Dancing' 'Cooking']

Mean:
[7.3 7.  7.6 7.3 4.8 4.6 4.9 3.6]

Median:
[7.5 7.  7.5 7.5 4.  4.  5.  3. ]

Standard Deviation:
[1.26885775 1.41421356 1.11355287 1.26885775 2.13541565 2.2
 2.02237484 1.49666295]

Maximum:
[9 9 9 9 9 9 8 6]

Minimum:
[5 5 6 5 2 2 2 2]


In [2]:
import pandas as pd
import numpy as np

# For reproducible random values
np.random.seed(42)

# Number of records
n = 100

# Create dataset
data = {
    "Student_ID": range(1, n + 1),

    "Age": np.random.randint(16, 30, n),

    "Study_Hours": np.round(
        np.random.uniform(1, 10, n), 1
    ),

    "Hobby_Hours": np.round(
        np.random.uniform(1, 15, n), 1
    ),

    "Hobby_Days": np.random.randint(1, 8, n),

    "Free_Time_Hours": np.round(
        np.random.uniform(1, 8, n), 1
    ),

    "Sleep_Hours": np.round(
        np.random.uniform(5, 9, n), 1
    ),

    "Energy_Level": np.random.randint(1, 11, n),

    "Hobby_Intensity": np.random.choice(
        ["Low", "Medium", "High"],
        n
    ),

    "New_Skills_Learned": np.random.randint(1, 16, n),

    "Mistakes_Per_Session": np.random.randint(0, 21, n),

    "Mood": np.random.choice(
        ["Happy", "Neutral", "Tired"],
        n
    ),

    "Previous_Score": np.round(
        np.random.uniform(40, 95, n), 1
    ),

    "Preferred_Hobby": np.random.choice(
        [
            "Reading",
            "Gaming",
            "Music",
            "Sports",
            "Dancing",
            "Cooking",
            "Drawing",
            "Photography"
        ],
        n
    )
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)


# --------------------------------------------------
# Create Hobby Performance Score
# --------------------------------------------------

df["Performance_Score"] = (
    30
    + df["Hobby_Hours"] * 2.5
    + df["Hobby_Days"] * 1.5
    + df["Free_Time_Hours"] * 0.3
    + df["Sleep_Hours"] * 2
    + df["Energy_Level"] * 1.5
    + df["Study_Hours"] * 1.5
    + df["New_Skills_Learned"] * 0.5
    + df["Previous_Score"] * 0.2
    - df["Mistakes_Per_Session"] * 1.2
)

# Add some random variation
df["Performance_Score"] += np.random.normal(0, 5, n)

# Keep score between 0 and 100
df["Performance_Score"] = (
    df["Performance_Score"]
    .clip(0, 100)
    .round(1)
)


# --------------------------------------------------
# Create ML Target
# --------------------------------------------------

df["Performance_Level"] = np.where(
    df["Performance_Score"] >= 70,
    "Good",
    "Needs Improvement"
)


# --------------------------------------------------
# Add a few missing values for data-cleaning practice
# --------------------------------------------------

df.loc[
    np.random.choice(n, 5, replace=False),
    "Sleep_Hours"
] = np.nan

df.loc[
    np.random.choice(n, 4, replace=False),
    "Mood"
] = np.nan

df.loc[
    np.random.choice(n, 3, replace=False),
    "Hobby_Hours"
] = np.nan


# --------------------------------------------------
# Save as CSV
# --------------------------------------------------

df.to_csv(
    "hobbies_performance_dataset.csv",
    index=False
)

print("CSV file created successfully!")
print("File name: hobbies_performance_dataset.csv")


# Display first 10 rows
print("\nFirst 10 rows:")
print(df.head(10))

CSV file created successfully!
File name: hobbies_performance_dataset.csv

First 10 rows:
   Student_ID  Age  Study_Hours  Hobby_Hours  Hobby_Days  Free_Time_Hours  \
0           1   22          2.8         11.7           2              4.0   
1           2   19          1.4          4.3           3              5.8   
2           3   28          3.9         11.2           6              1.4   
3           4   26          4.5          6.1           2              7.4   
4           5   23          3.4          9.9           7              4.1   
5           6   28          8.5          9.9           6              2.7   
6           7   20          4.2          8.5           7              1.7   
7           8   22          3.5          2.3           2              2.3   
8           9   25          5.9         12.7           7              7.5   
9          10   18          2.3          5.5           3              5.5   

   Sleep_Hours  Energy_Level Hobby_Intensity  New_Skills_Learn